# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/


build:arch:
  image: archlinux/base
  stage: build
  before_script:
    - pacman -Syu --noconfirm
    - pacman -S base-devel boost cmake gcc clang git curl wget pugixml --noconfirm
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build
           
test:arch:
  stage: test
  before_script:
    - pacman -Syu --noconfirm
    - pacman -S base-devel boost cmake gcc clang git curl wget --noconfirm
    - pacman -S pugixml --noconfirm
  script:
    - cd build
    - ctest
  dependencies:
    - build:arch
    
build:ubuntu:focal
  image: ubuntu:20.04
  stage: build
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y libboost-all-devel cmake gcc clang git curl wget pugixml-dev
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build
    
test:ubuntu:focal:
  stage: test
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y libboost-all-devel cmake gcc clang git curl wget pugixml-dev
  script:
    - cd build
    - ctest
  dependencies:
    - build:ubuntu:focal
