stages:
  - build
  - test

build:arch:
  image: archlinux/base
  stage: build
  before_script:
    - pacman -Syu --noconfirm
    - pacman -S base-devel boost cmake gcc clang git curl wget pugixml --noconfirm
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build
           
test:arch:
  stage: test
  before_script:
    - pacman -Syu --noconfirm
    - pacman -S base-devel boost cmake gcc clang git curl wget --noconfirm
    - pacman -S pugixml --noconfirm
  script:
    - cd build
    - ctest
  dependencies:
    - build:arch
    
build:ubuntu:focal:
  image: ubuntu:20.04
  stage: build
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
    - apt-get install -y tzdata
    - dpkg-reconfigure --frontend noninteractive tzdata
    - apt-get install -y build-essential checkinstall zlib1g-dev 
    - apt-get install -y libboost-all-dev cmake gcc clang git curl wget libssl-dev libpugixml-dev
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build
    
test:ubuntu:focal:
  stage: test
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
    - apt-get install -y tzdata
    - dpkg-reconfigure --frontend noninteractive tzdata
    - apt-get install -y build-essential checkinstall zlib1g-dev 
    - apt-get install -y libboost-all-dev cmake gcc clang git curl wget libssl-dev libpugixml-dev
  script:
    - cd build
    - ctest
  dependencies:
    - build:ubuntu:focal
